build: false

environment:
  matrix:
    # 64 bit
      ## msvc
    - BITS: 64
      CHANNEL: beta
      TARGET: x86_64-pc-windows-msvc
    - BITS: 64
      CHANNEL: nightly
      TARGET: x86_64-pc-windows-msvc
    - BITS: 64
      CHANNEL: stable
      TARGET: x86_64-pc-windows-msvc
      ## gnu
    - BITS: 64
      CHANNEL: beta
      TARGET: x86_64-pc-windows-gnu
    - BITS: 64
      CHANNEL: nightly
      TARGET: x86_64-pc-windows-gnu
    - BITS: 64
      CHANNEL: stable
      TARGET: x86_64-pc-windows-gnu

    # 32 bit
      ## msvc
    - BITS: 32
      CHANNEL: beta
      TARGET: i686-pc-windows-msvc
    - BITS: 32
      CHANNEL: nightly
      target: i686-pc-windows-msvc
    - BITS: 32
      CHANNEL: stable
      TARGET: i686-pc-windows-msvc
      ## gnu
    - BITS: 32
      CHANNEL: beta
      TARGET: i686-pc-windows-gnu
    - BITS: 32
      CHANNEL: nightly
      TARGET: i686-pc-windows-gnu
    - BITS: 32
      CHANNEL: stable
      TARGET: i686-pc-windows-gnu

install:
  - set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

matrix:
  allow_failures:
    - channel: nightly

os: Visual Studio 2017

test_script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
